name: CI
on: [ push ]
jobs:
  build:
    strategy:
      matrix:
        os: [ windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
        cache: 'yarn'
    - name: Intall dependencies
      run: yarn install --frozen-lockfile
