# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Publish package

on:
  push:
    branches: [ "master" ]

jobs:
  publish:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Enable Corepack before setting up Node
      run: corepack enable
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'yarn'
        architecture: 'x64'
    - name: Install dependencies
      run: yarn install
    - name: Build and publish package
      run: yarn run publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
